- name: Cleanup the lab
  hosts: localhost
  connection: local
  tasks:
  - name: Destroy the LXD containers
    lxd_container:
      name: '{{ item }}'
      state: absent
    with_items:
      - '{{ groups.containers }}'

#  - name: Clean up /etc/hosts
#    lineinfile:
#      path: /etc/hosts
#      state: absent
#      regex: '^([0-9]{1,3}\.){3}[0-9]{1,3}([ ]{1,}){{ item }}'
#    with_items:
#      - '{{ groups.containers }}'
